"""add system flag and indexes for future dashboards

Revision ID: 2695ad242410
Revises: 679025a574c6
Create Date: 2026-03-16 23:14:52.806393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2695ad242410'
down_revision: Union[str, Sequence[str], None] = '679025a574c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('employee_id', sa.UUID(), nullable=True))
    op.create_index('ix_appointments_business_employee_time', 'appointments', ['business_id', 'employee_id', 'start_at'], unique=False)
    op.create_index('ix_appointments_business_status', 'appointments', ['business_id', 'status'], unique=False)
    op.create_index('ix_appointments_business_time', 'appointments', ['business_id', 'start_at'], unique=False)
    op.create_index(op.f('ix_appointments_employee_id'), 'appointments', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'users', ['employee_id'], ['id'])
    op.add_column('roles', sa.Column('is_business_admin', sa.Boolean(), nullable=False))
    op.drop_column('roles', 'superuser')
    op.add_column('users', sa.Column('is_system_admin', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_system_admin')
    op.add_column('roles', sa.Column('superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('roles', 'is_business_admin')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_employee_id'), table_name='appointments')
    op.drop_index('ix_appointments_business_time', table_name='appointments')
    op.drop_index('ix_appointments_business_status', table_name='appointments')
    op.drop_index('ix_appointments_business_employee_time', table_name='appointments')
    op.drop_column('appointments', 'employee_id')
    # ### end Alembic commands ###
