"""add change to role table

Revision ID: 28e92b122e7e
Revises: 2695ad242410
Create Date: 2026-03-27 01:45:01.642525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e92b122e7e'
down_revision: Union[str, Sequence[str], None] = '2695ad242410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'permissions',
               existing_type=sa.ARRAY(sa.String()),
               server_default='{}',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'permissions',
               existing_type=sa.ARRAY(sa.String()),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
