"""client tables reputation and clients

Revision ID: 2ddf1e2d6c88
Revises: 7e49913c87b5
Create Date: 2026-03-16 21:47:54.376613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ddf1e2d6c88'
down_revision: Union[str, Sequence[str], None] = '7e49913c87b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_members_business_id'), 'business_members', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_members_role_id'), 'business_members', ['role_id'], unique=False)
    op.create_index(op.f('ix_business_members_user_id'), 'business_members', ['user_id'], unique=False)
    op.create_table('client_reputation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporting_business_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('is_locally_blocked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reporting_business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_reputation_email'), 'client_reputation', ['email'], unique=False)
    op.create_index(op.f('ix_client_reputation_phone'), 'client_reputation', ['phone'], unique=False)
    op.create_index(op.f('ix_client_reputation_reporting_business_id'), 'client_reputation', ['reporting_business_id'], unique=False)
    op.create_index('ix_unique_reputation_per_business', 'client_reputation', ['reporting_business_id', 'phone'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_business_phone', 'clients', ['business_id', 'phone'], unique=True)
    op.create_index(op.f('ix_clients_business_id'), 'clients', ['business_id'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_business_id'), table_name='clients')
    op.drop_index('ix_client_business_phone', table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_unique_reputation_per_business', table_name='client_reputation')
    op.drop_index(op.f('ix_client_reputation_reporting_business_id'), table_name='client_reputation')
    op.drop_index(op.f('ix_client_reputation_phone'), table_name='client_reputation')
    op.drop_index(op.f('ix_client_reputation_email'), table_name='client_reputation')
    op.drop_table('client_reputation')
    op.drop_index(op.f('ix_business_members_user_id'), table_name='business_members')
    op.drop_index(op.f('ix_business_members_role_id'), table_name='business_members')
    op.drop_index(op.f('ix_business_members_business_id'), table_name='business_members')
    op.drop_table('business_members')
    # ### end Alembic commands ###
