"""update role model with permissions

Revision ID: 57167cda14cd
Revises: 6c38a15b2df5
Create Date: 2026-03-16 22:44:13.650175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57167cda14cd'
down_revision: Union[str, Sequence[str], None] = '6c38a15b2df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('business_id', sa.UUID(), nullable=True))
    op.add_column('roles', sa.Column('permissions', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_business_id'), 'roles', ['business_id'], unique=False)
    op.create_index('ix_roles_business_name', 'roles', ['business_id', 'name'], unique=True)
    op.create_foreign_key(None, 'roles', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_index('ix_roles_business_name', table_name='roles')
    op.drop_index(op.f('ix_roles_business_id'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'business_id')
    # ### end Alembic commands ###
